import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { PGlite } from '@electric-sql/pglite';
import { OperationService, OperationError, normalizeCommand, revisionToken, canonical, type Database, type QueryClient } from '../src/services/operationService.js';
import { attachContact, CheckinController } from '../src/controllers/checkinController.js';
import { ContactController } from '../src/controllers/contactController.js';
import { pool } from '../src/config/db.js';
import { swaggerDocument } from '../src/docs/swagger.js';
import { corsOptions } from '../src/middleware/cors.js';
import { formatResponseIntegers } from '../src/utils/responseFormatting.js';
import { createApp } from '../src/app.js';
import { once } from 'node:events';

let pg: PGlite;
let service: OperationService;
const actor = {uid:'jane-account',staff:false};
const staff = {uid:'staff-account',staff:true};
let sequence = 0;
function uuid7(time = Date.now()): string {
  const hex = Math.trunc(time).toString(16).padStart(12,'0');
  return `${hex.slice(0,8)}-${hex.slice(8)}-7${randomUUID().slice(15,18)}-8${randomUUID().slice(20,23)}-${randomUUID().slice(-12)}`;
}
const run = async (sql:string, params:any[] = []) => pg.query<any>(sql,params);
const item = (resource:string,id:number|string,action='PUT') => ({resource,record_id:String(id),action});
async function seed() {
  const id = ++sequence;
  await run('INSERT INTO contacts(id,name,emails,phones,zip_home,roles,firebase_uid) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,'JANE DOE',['jane@example.invalid'],['+1-214-555-0100'],'75001',['member'],actor.uid]);
  await run("INSERT INTO checkins(id,contact_id,event_id,submitted_on) VALUES($1,$1,1,'2026-10-03 18:00:00.123456+00')",[id]);
  return id;
}
async function revision(resource:string,id:number|string) {
  const r = await run('SELECT incarnation::text,revision::text FROM resource_revisions WHERE resource=$1 AND record_id=$2',[resource,String(id)]);
  return revisionToken(r.rows[0]);
}
async function begin(manifest:any[], who=actor, overrides:any={}) {
  return service.begin(who,{client_action_id:uuid7(),source:'event-view',action_type:'save',event_id:'1',manifest,...overrides},randomUUID());
}
async function stage(group:any,resource:'contacts'|'checkins',id:number,body:any,action:'PUT'|'DELETE'='PUT',who=actor,key=randomUUID()) {
  return service.mutate(who,resource,id,action,body,{id:group.group_id,match:`"${await revision(resource,id)}"`,key});
}
async function committed(id:number,body:any,who=actor) {
  const group = await begin([item('contacts',id)],who);
  await stage(group,'contacts',id,body,'PUT',who);
  return service.commit(who,group.group_id,randomUUID());
}
async function error(promise:Promise<any>,status:number,code?:string) {
  await assert.rejects(promise,(e:any) => e instanceof OperationError && e.status===status && (!code || e.code===code));
}
before(async () => {
  pg = new PGlite();
  await pg.exec(`CREATE TABLE events(id bigint PRIMARY KEY,start_at timestamptz NOT NULL,end_at timestamptz,title text);
    CREATE TABLE contacts(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name text NOT NULL,created_on timestamptz DEFAULT clock_timestamp(),emails text[],phones text[],zip_home text,zip_other text[],roles text[],firebase_uid text);
    CREATE TABLE checkins(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,contact_id bigint REFERENCES contacts(id),event_id bigint NOT NULL REFERENCES events(id),submitted_on timestamptz NOT NULL);
    INSERT INTO events VALUES(1,'2026-10-03 18:00Z','2026-10-03 20:00Z','Test'),(2,'2026-10-03 18:00Z',NULL,'No end');`);
  await pg.exec(await readFile(new URL('../migrations/003_operation_groups.sql',import.meta.url),'utf8'));
  let queue = Promise.resolve();
  const db: Database = {
    query:(text,values) => run(text,values),
    async connect() {
      let unlock!: () => void;
      const previous = queue; queue = new Promise<void>(resolve => {unlock=resolve;}); await previous;
      return {query:(text,values) => run(text,values),release:unlock} as QueryClient;
    }
  };
  service = new OperationService(db);
});
after(async () => { await pg.close(); });

test('self marker and narrow name exception never reveal other fields', () => {
  const row = {id:1,firebase_uid:actor.uid,contact:{id:2,name:'JANE DOE',emails:['private'],phones:['private'],roles:['staff'],firebase_uid:actor.uid,zip_home:'75001',secret_new_column:'hidden'}};
  const self = attachContact(row,'redacted',actor.uid,true);
  assert.equal(self.is_self,true); assert.equal(self.contact.name,'JANE DOE'); assert.equal(self.contact.emails,null);
  assert.equal(self.firebase_uid,undefined); assert.equal(self.contact.secret_new_column,undefined);
  assert.equal(attachContact(row,'redacted','different',true).is_self,false);
  assert.notEqual(attachContact(row,'redacted','different',true).contact.name,'JANE DOE');
  assert.equal(attachContact(row,'false',actor.uid,true).contact,undefined);
  assert.equal(attachContact({...row,firebase_uid:null},'redacted',actor.uid,true).is_self,false);
  assert.equal(attachContact(row,'redacted').is_self,false);
});

test('ordinary authorized partial contact updates preserve omission and protected fields',async () => {
  const id=await seed();
  await service.mutate(actor,'contacts',id,'PUT',{name:' jane smith ',roles:[],firebase_uid:''});
  const contact=(await run('SELECT * FROM contacts WHERE id=$1',[id])).rows[0];
  assert.equal(contact.name,'JANE SMITH'); assert.deepEqual(contact.roles,['member']); assert.deepEqual(contact.emails,['jane@example.invalid']); assert.equal(contact.firebase_uid,actor.uid);
  await service.mutate(actor,'contacts',id,'PUT',{phones:[],zip_home:''});
  const cleared=(await run('SELECT * FROM contacts WHERE id=$1',[id])).rows[0]; assert.equal(cleared.phones,null); assert.equal(cleared.zip_home,null);
  await error(service.mutate(actor,'contacts',id,'PUT',{name:''}),400,'INVALID_NAME');
  await error(service.mutate(actor,'contacts',id,'PUT',{phones:[123]}),400,'INVALID_FIELD');
  await error(service.mutate(actor,'contacts',id,'PUT',{}),400,'EMPTY_UPDATE');
});

test('staff omission preserves roles/UID and explicit clearing is allowed',async () => {
  const id=await seed(); await service.mutate(staff,'contacts',id,'PUT',{zip_home:'75201'});
  assert.equal((await run('SELECT firebase_uid FROM contacts WHERE id=$1',[id])).rows[0].firebase_uid,actor.uid);
  await service.mutate(staff,'contacts',id,'PUT',{roles:null,firebase_uid:''});
  const row=(await run('SELECT roles,firebase_uid FROM contacts WHERE id=$1',[id])).rows[0]; assert.equal(row.roles,null); assert.equal(row.firebase_uid,null);
});

test('timestamp bounds are inclusive, offset aware, preserve microseconds, and no-end fallback applies',async () => {
  const id=await seed();
  for (const submitted_on of ['2026-10-03T16:00:00Z','2026-10-03T21:00:00Z','2026-10-03T16:00:00-05:00']) await service.mutate(actor,'checkins',id,'PUT',{submitted_on});
  for (const submitted_on of ['2026-10-03T15:59:59.999999Z','2026-10-03T21:00:00.000001Z']) await error(service.mutate(actor,'checkins',id,'PUT',{submitted_on}),400,'TIMESTAMP_OUT_OF_BOUNDS');
  for (const submitted_on of [null,'','2026-10-03','2026-10-03T18:00:00','2026-02-30T18:00:00Z']) await error(service.mutate(actor,'checkins',id,'PUT',{submitted_on}),400,'INVALID_TIMESTAMP');
  await service.mutate(actor,'checkins',id,'PUT',{event_id:'2',submitted_on:'2026-10-03T22:00:00Z'});
  await error(service.mutate(actor,'checkins',id,'PUT',{submitted_on:'2026-10-03T22:00:00.000001Z'}),400);
  await error(service.mutate(actor,'checkins',id,'PUT',{event_id:'1'}),400);
  await service.mutate(actor,'checkins',id,'PUT',{submitted_on:'2026-10-03T18:00:00.123456Z'});
  assert.match((await run('SELECT submitted_on::text AS stamp FROM checkins WHERE id=$1',[id])).rows[0].stamp,/\.123456/);
});

test('five-item manifest cannot commit with four stages, retries/unexpected/duplicate do not complete it',async () => {
  const ids=[]; for(let i=0;i<5;i++) ids.push(await seed());
  const group=await begin(ids.map(id=>item('contacts',id)));
  const stageKey=randomUUID(); const match=await revision('contacts',ids[0]);
  const request={id:group.group_id,match,key:stageKey};
  const first=await service.mutate(actor,'contacts',ids[0],'PUT',{zip_home:'75202'},request);
  assert.deepEqual(await service.mutate(actor,'contacts',ids[0],'PUT',{zip_home:'75202'},request),first);
  await error(stage(group,'contacts',ids[0],{zip_home:'75202'}),409,'DUPLICATE_TARGET');
  await error(stage(group,'checkins',ids[0],{submitted_on:'2026-10-03T19:00:00Z'}),409,'OUTSIDE_MANIFEST');
  await error(stage(group,'contacts',ids[4],{},'DELETE'),409,'OUTSIDE_MANIFEST');
  for(const id of ids.slice(1,4)) await stage(group,'contacts',id,{zip_home:'75202'});
  const commitKey=randomUUID(); await error(service.commit(actor,group.group_id,commitKey),409,'MANIFEST_INCOMPLETE');
  assert.equal((await run('SELECT count(*)::integer AS n FROM contacts WHERE id=ANY($1) AND zip_home=$2',[ids,'75001'])).rows[0].n,5);
  await stage(group,'contacts',ids[4],{zip_home:'75202'});
  const receipt=await service.commit(actor,group.group_id,commitKey); assert.equal(receipt.affected_record_count,5);
  assert.equal((await service.status(actor,group.group_id)).status,'committed');
});

test('manifest identities not counts determine completeness, duplicate manifest rejected',async () => {
  const a=await seed(), b=await seed();
  await error(begin([item('contacts',a),item('contacts',a,'DELETE')]),409,'DUPLICATE_TARGET');
  const group=await begin([item('contacts',a),item('contacts',b)]);
  await stage(group,'contacts',a,{zip_home:'75203'}); await stage(group,'contacts',b,{zip_home:'75203'});
  await run("UPDATE operation_items SET action='DELETE' WHERE group_id=$1 AND record_id=$2",[group.group_id,b]);
  await error(service.commit(actor,group.group_id,randomUUID()),409,'MANIFEST_INCOMPLETE');
  assert.equal((await run('SELECT zip_home FROM contacts WHERE id=$1',[a])).rows[0].zip_home,'75001');
});

test('grouped ownership, revision preconditions, current staff role and dependencies enforced',async () => {
  const id=await seed(); const group=await begin([item('contacts',id)]);
  await error(stage(group,'contacts',id,{zip_home:'1'},'PUT',{uid:'other',staff:false}),404);
  await error(service.mutate(actor,'contacts',id,'PUT',{zip_home:'1'},{id:group.group_id,match:undefined,key:randomUUID()}),428);
  const stale=await revision('contacts',id); await service.mutate(actor,'contacts',id,'PUT',{zip_home:'2'});
  await error(service.mutate(actor,'contacts',id,'PUT',{zip_home:'1'},{id:group.group_id,match:stale,key:randomUUID()}),409,'REVISION_CONFLICT');
  const staffGroup=await begin([item('contacts',id)],staff); await stage(staffGroup,'contacts',id,{roles:['staff']},'PUT',staff);
  await error(service.commit({...staff,staff:false},staffGroup.group_id,randomUUID()),403,'PERMISSION_REVOKED');
  const checkGroup=await begin([item('checkins',id)]); await stage(checkGroup,'checkins',id,{submitted_on:'2026-10-03T19:00:00Z'});
  await run("UPDATE events SET title='changed' WHERE id=1");
  await error(service.commit(actor,checkGroup.group_id,randomUUID()),409,'REVISION_CONFLICT');
});

test('ordinary writes are immediate and invalidate stage and Undo even after edit-then-revert',async () => {
  const id=await seed(); const a=await committed(id,{zip_home:'75204'});
  await service.mutate(actor,'contacts',id,'PUT',{zip_home:'75205'}); await service.mutate(actor,'contacts',id,'PUT',{zip_home:'75204'});
  await error(service.undo(actor,a.group_id,randomUUID()),409,'UNDO_CONFLICT');
  const history=await service.history(actor,{source:'event-view'});
  assert.deepEqual(history.items.find((g:any)=>g.group_id===a.group_id).undo_restrictions,['UNDO_CONFLICT']);
});

test('overlapping saves undo in reverse order with new revisions and no new undoable action',async () => {
  const id=await seed(); const a=await committed(id,{phones:['2145550101']}); const aRev=await revision('contacts',id);
  const b=await committed(id,{zip_home:'75206'});
  await error(service.undo(actor,a.group_id,randomUUID()),409,'UNDO_CONFLICT');
  await service.undo(actor,b.group_id,randomUUID()); assert.notEqual(await revision('contacts',id),aRev);
  const key=randomUUID(); const receipt=await service.undo(actor,a.group_id,key); const finalRevision=await revision('contacts',id);
  assert.deepEqual(await service.undo(actor,a.group_id,key),receipt); assert.equal(await revision('contacts',id),finalRevision);
  assert.deepEqual((await run('SELECT phones FROM contacts WHERE id=$1',[id])).rows[0].phones,['+1-214-555-0100']);
  assert.equal((await service.status(actor,a.group_id)).status,'undone');
  assert.equal((await run('SELECT count(*)::integer AS n FROM operation_inverse_receipts WHERE group_id=ANY($1::uuid[])',[[a.group_id,b.group_id]])).rows[0].n,2);
});

test('ordinary barrier between saves is not erased by Undo of the later save',async () => {
  const id=await seed(); const a=await committed(id,{zip_home:'75207'});
  await service.mutate(actor,'contacts',id,'PUT',{zip_home:'75208'}); await service.mutate(actor,'contacts',id,'PUT',{zip_home:'75207'});
  const b=await committed(id,{phones:['2145550102']}); await service.undo(actor,b.group_id,randomUUID());
  await error(service.undo(actor,a.group_id,randomUUID()),409,'UNDO_CONFLICT');
});

test('overlapping multi-record groups restore every target or none',async () => {
  const jane=await seed(),sam=await seed(),alex=await seed();
  const a=await begin([item('contacts',jane),item('contacts',sam)]); for(const id of [jane,sam]) await stage(a,'contacts',id,{zip_home:'75209'}); await service.commit(actor,a.group_id,randomUUID());
  const b=await begin([item('contacts',jane),item('contacts',alex)]); for(const id of [jane,alex]) await stage(b,'contacts',id,{phones:['2145550103']}); await service.commit(actor,b.group_id,randomUUID());
  await service.undo(actor,b.group_id,randomUUID());
  await service.mutate(actor,'contacts',sam,'PUT',{zip_home:'75210'});
  const janeRevision=await revision('contacts',jane);
  await error(service.undo(actor,a.group_id,randomUUID()),409,'UNDO_CONFLICT'); assert.equal(await revision('contacts',jane),janeRevision);
  assert.equal((await run('SELECT zip_home FROM contacts WHERE id=$1',[jane])).rows[0].zip_home,'75209');
});

test('contact and check-in group validates own dependencies and exact deletion restore',async () => {
  const id=await seed(); const group=await begin([item('contacts',id,'DELETE'),item('checkins',id,'DELETE')]);
  await stage(group,'contacts',id,{},'DELETE'); await stage(group,'checkins',id,{},'DELETE');
  await service.commit(actor,group.group_id,randomUUID()); assert.equal((await run('SELECT * FROM checkins WHERE id=$1',[id])).rows.length,0);
  await service.undo(actor,group.group_id,randomUUID());
  assert.equal((await run('SELECT firebase_uid FROM contacts WHERE id=$1',[id])).rows[0].firebase_uid,actor.uid);
  assert.match((await run('SELECT submitted_on::text AS stamp FROM checkins WHERE id=$1',[id])).rows[0].stamp,/\.123456/);
});

test('duplicate check-in created after deletion blocks restoration atomically',async () => {
  const id=await seed(); const group=await begin([item('checkins',id,'DELETE')]); await stage(group,'checkins',id,{},'DELETE'); await service.commit(actor,group.group_id,randomUUID());
  const other=++sequence; await run("INSERT INTO checkins VALUES($1,$2,1,'2026-10-03 19:00Z')",[other,id]);
  const token=await revision('checkins',id); await error(service.undo(actor,group.group_id,randomUUID()),409,'RESTORATION_CONFLICT');
  assert.equal(await revision('checkins',id),token); assert.equal((await service.status(actor,group.group_id)).status,'committed');
});

test('ordinary deleted-ID recreation cannot impersonate trusted lineage',async () => {
  const id=await seed(); const group=await begin([item('checkins',id,'DELETE')]); await stage(group,'checkins',id,{},'DELETE'); await service.commit(actor,group.group_id,randomUUID());
  await run("INSERT INTO checkins VALUES($1,$1,1,'2026-10-03 18:00:00.123456Z')",[id]);
  await error(service.undo(actor,group.group_id,randomUUID()),409,'UNDO_CONFLICT');
});

test('committed lost response is discoverable with no local snapshot or group ID and inverse executes once',async () => {
  const id=await seed(); const before=(await run('SELECT zip_home FROM contacts WHERE id=$1',[id])).rows[0].zip_home;
  const group=await begin([item('contacts',id)],actor,{source:'recovery-test'}); await stage(group,'contacts',id,{zip_home:'75211'});
  await service.commit(actor,group.group_id,randomUUID()); // Discard the entire commit response.
  const freshFrontend=await service.history(actor,{source:'recovery-test'}); assert.equal(freshFrontend.items.length,1);
  const action=freshFrontend.items[0]; assert.equal(action.client_action_id,group.client_action_id); assert.equal(action.preimage,undefined);
  const undoKey=randomUUID(); await service.undo(actor,action.group_id,undoKey); const token=await revision('contacts',id);
  await service.undo(actor,action.group_id,undoKey); assert.equal(await revision('contacts',id),token);
  assert.equal((await run('SELECT zip_home FROM contacts WHERE id=$1',[id])).rows[0].zip_home,before);
});

test('history pagination is account/source scoped, high-water stable and rejects forged cursors',async () => {
  for(let i=0;i<3;i++) {const id=await seed(); const group=await begin([item('contacts',id)],actor,{source:'pages'}); await stage(group,'contacts',id,{zip_home:'75212'}); await service.commit(actor,group.group_id,randomUUID());}
  const page1=await service.history(actor,{source:'pages',limit:2}); assert.equal(page1.items.length,2); assert.ok(page1.next_cursor);
  const id=await seed(); const group=await begin([item('contacts',id)],actor,{source:'pages'}); await stage(group,'contacts',id,{zip_home:'75213'}); await service.commit(actor,group.group_id,randomUUID());
  const page2=await service.history(actor,{source:'pages',limit:2,cursor:page1.next_cursor}); assert.equal(page2.items.length,1); assert.equal(page2.next_cursor,null);
  assert.ok(BigInt(page2.items[0].commit_order)<BigInt(page1.items[1].commit_order));
  await error(service.history({uid:'other',staff:true},{source:'pages',cursor:page1.next_cursor}),400,'INVALID_CURSOR');
  await error(service.history(actor,{source:'other',cursor:page1.next_cursor}),400,'INVALID_CURSOR');
  await error(service.history(actor,{source:'pages',cursor:randomUUID()}),400,'INVALID_CURSOR');
  assert.deepEqual((await service.history({uid:'other',staff:true},{source:'pages'})).items,[]);
});

test('Ctrl-Z latest preconditions reject stale tab and blocked latest without falling back',async () => {
  const id=await seed(); const a=await committed(id,{zip_home:'75214'}); const b=await committed(id,{phones:['2145550104']});
  await error(service.undo(actor,a.group_id,randomUUID(),{source:'event-view',expected_latest_group_id:a.group_id,expected_latest_commit_order:a.commit_order}),409,'LATEST_ACTION_CHANGED');
  const input={source:'event-view',expected_latest_group_id:b.group_id,expected_latest_commit_order:b.commit_order};
  const key=randomUUID(); await service.undo(actor,b.group_id,key,input); const token=await revision('contacts',id);
  await service.undo(actor,b.group_id,key,input); assert.equal(await revision('contacts',id),token);
  await service.mutate(actor,'contacts',id,'PUT',{zip_home:'75215'});
  await error(service.undo(actor,a.group_id,randomUUID(),{source:'event-view',expected_latest_group_id:a.group_id,expected_latest_commit_order:a.commit_order}),409,'UNDO_CONFLICT');
});

test('expiry uses database deadlines, retry horizon prevents cleaned action re-execution',async () => {
  const id=await seed(); const group=await begin([item('contacts',id)]);
  await run("UPDATE operation_groups SET open_expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[group.group_id]);
  await error(stage(group,'contacts',id,{zip_home:'75216'}),410,'GROUP_EXPIRED'); await error(service.commit(actor,group.group_id,randomUUID()),410,'GROUP_EXPIRED');
  const receipt=await committed(id,{zip_home:'75217'});
  await run("UPDATE operation_groups SET undo_expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[receipt.group_id]);
  await error(service.undo(actor,receipt.group_id,randomUUID()),410,'UNDO_EXPIRED');
  assert.equal((await service.history(actor,{source:'event-view'})).items.some((g:any)=>g.group_id===receipt.group_id),false);
  await error(begin([item('contacts',id)],actor,{client_action_id:uuid7(Date.now()-91*86_400_000)}),410,'RETRY_HORIZON_EXPIRED');
});

test('limits count distinct typed targets and canonical UTF8 bytes; oversized stage never changes records',async () => {
  const id=await seed();
  await error(begin(Array.from({length:101},(_,i)=>item('contacts',i+1))),413,'GROUP_LIMIT_EXCEEDED');
  const group=await begin([item('contacts',id),item('checkins',id)]); // Same numeric ID, separate targets.
  const huge='é'.repeat(524288); const before=await revision('contacts',id);
  await error(stage(group,'contacts',id,{name:huge}),413,'GROUP_LIMIT_EXCEEDED'); assert.equal(await revision('contacts',id),before);
  const request={resource:'contacts',record_id:String(id),action:'PUT',command:{zip_home:'75218'}};
  const key=randomUUID(); const match=await revision('contacts',id); const options={id:group.group_id,match,key};
  await service.mutate(actor,'contacts',id,'PUT',{zip_home:'75218'},options);
  await service.mutate(actor,'contacts',id,'PUT',{zip_home:'75218'},options);
  assert.equal((await service.status(actor,group.group_id)).payload_bytes,group.payload_bytes+Buffer.byteLength(canonical(request),'utf8'));
});

test('begin action identity and transport retries cannot duplicate or change manifests',async () => {
  const id=await seed(); const body={client_action_id:uuid7(),source:'event-view',action_type:'save',event_id:'1',manifest:[item('contacts',id)]}; const key=randomUUID();
  const a=await service.begin(actor,body,key); assert.deepEqual(await service.begin(actor,body,key),a);
  assert.equal((await service.begin(actor,body,randomUUID())).group_id,a.group_id);
  await error(service.begin(actor,{...body,action_type:'remove'},key),409,'IDEMPOTENCY_CONFLICT');
  await error(service.begin(actor,{...body,manifest:[item('contacts',id,'DELETE')]},randomUUID()),409,'ACTION_ID_CONFLICT');
});


test('actual record reads expose consistent revisions, self redaction, and ETags',async () => {
  const id=await seed(); const original=pool.query;
  (pool as any).query=run;
  const request=(query:any={}) => ({query,params:{id:String(id)},user:{uid:actor.uid,roles:[]}} as any);
  const response=() => {
    const result:any={headers:{}};
    result.setHeader=(k:string,v:any) => {result.headers[k]=v;};
    result.status=(code:number) => {result.code=code; return result;};
    result.json=(body:any) => {result.body=body; return result;};
    return result;
  };
  const next=(e:any) => {if(e) throw e;};
  try {
    const list=response(); await CheckinController.getAllCheckins(request({event_id:'1',contact_id:String(id),include_contact:'full'}),list,next);
    assert.equal(list.code,200); assert.equal(list.body[0].is_self,true); assert.equal(list.body[0].contact.name,'JANE DOE'); assert.equal(list.body[0].contact.emails,null); assert.equal(list.body[0].firebase_uid,undefined);
    const bare=response(); await CheckinController.getAllCheckins(request({event_id:'1',contact_id:String(id)}),bare,next); assert.equal(bare.body[0].contact,undefined); assert.equal(bare.body[0].is_self,true);
    const single=response(); await CheckinController.getCheckinById(request(),single,next); assert.equal(single.code,200); assert.equal(single.headers.ETag,`"${await revision('checkins',id)}"`);
    const contact=response(); await ContactController.getContactById(request(),contact,next); assert.equal(contact.code,200); assert.equal(contact.headers.ETag,`"${await revision('contacts',id)}"`); assert.equal(contact.body.name,'JANE DOE');
    const search=response(); await ContactController.getAllContacts({...request({name:'JANE'}),user:{uid:'staff',roles:['staff']}} as any,search,next); assert.equal(search.code,200); assert.ok(search.body.find((c:any)=>String(c.id)===String(id)).revision);
    const noOwner=response(); await ContactController.updateContact({...request(),user:undefined,body:{emails:null,phones:'',zip_home:''},header:()=>undefined} as any,noOwner,next);
    assert.equal(noOwner.code,200); const stored=(await run('SELECT emails,phones,zip_home FROM contacts WHERE id=$1',[id])).rows[0]; assert.deepEqual(stored.emails,['jane@example.invalid']); assert.deepEqual(stored.phones,['+1-214-555-0100']); assert.equal(stored.zip_home,'75001');
    const grouped=response(); await ContactController.updateContact({...request(),user:undefined,body:{phones:[]},header:(name:string)=>name==='X-Operation-Group'?randomUUID():undefined} as any,grouped,next); assert.equal(grouped.code,401);
  } finally {(pool as any).query=original;}
});

test('late application failure rolls back earlier records, revisions, and discoverable history',async () => {
  const a=await seed(),b=await seed(); const group=await begin([item('contacts',a),item('contacts',b)]);
  await stage(group,'contacts',a,{zip_home:'75219'}); await stage(group,'contacts',b,{zip_home:'75219'});
  const token=await revision('contacts',a);
  await pg.exec(`CREATE FUNCTION test_fail_write() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.id=${b} THEN RAISE EXCEPTION 'test failure' USING ERRCODE='23514'; END IF; RETURN NEW; END $$; CREATE TRIGGER test_failure BEFORE UPDATE ON contacts FOR EACH ROW EXECUTE FUNCTION test_fail_write();`);
  try {await error(service.commit(actor,group.group_id,randomUUID()),409,'RESTORATION_CONFLICT');}
  finally {await pg.exec('DROP TRIGGER test_failure ON contacts; DROP FUNCTION test_fail_write();');}
  assert.equal(await revision('contacts',a),token); assert.equal((await run('SELECT zip_home FROM contacts WHERE id=$1',[a])).rows[0].zip_home,'75001');
  assert.equal((await service.status(actor,group.group_id)).status,'open'); assert.equal((await service.history(actor,{source:'event-view'})).items.some((g:any)=>g.group_id===group.group_id),false);
});

test('successful overlapping multi-record inverses and dependency lineage restore earlier eligibility',async () => {
  const a=await seed(),b=await seed(),c=await seed();
  const first=await begin([item('contacts',a),item('contacts',b),item('checkins',a)]);
  await stage(first,'contacts',a,{phones:['2145550105']}); await stage(first,'contacts',b,{zip_home:'75220'}); await stage(first,'checkins',a,{submitted_on:'2026-10-03T19:00:00Z'}); await service.commit(actor,first.group_id,randomUUID());
  const second=await begin([item('contacts',a),item('contacts',c)]);
  await stage(second,'contacts',a,{zip_home:'75221'}); await stage(second,'contacts',c,{phones:['2145550106']}); await service.commit(actor,second.group_id,randomUUID());
  await service.undo(actor,second.group_id,randomUUID()); await service.undo(actor,first.group_id,randomUUID());
  assert.deepEqual((await run('SELECT phones FROM contacts WHERE id=$1',[a])).rows[0].phones,['+1-214-555-0100']); assert.match((await run('SELECT submitted_on::text AS stamp FROM checkins WHERE id=$1',[a])).rows[0].stamp,/\.123456/);
});

test('concurrent duplicate commits and inverse retries execute once',async () => {
  const id=await seed(); const group=await begin([item('contacts',id)]); await stage(group,'contacts',id,{zip_home:'75222'});
  const key=randomUUID(); const [a,b]=await Promise.all([service.commit(actor,group.group_id,key),service.commit(actor,group.group_id,key)]); assert.deepEqual(a,b);
  const before=await revision('contacts',id); const inverse=randomUUID(); const [x,y]=await Promise.all([service.undo(actor,group.group_id,inverse),service.undo(actor,group.group_id,inverse)]); assert.deepEqual(x,y); assert.notEqual(await revision('contacts',id),before);
  assert.equal((await run('SELECT count(*)::integer AS n FROM operation_inverse_receipts WHERE group_id=$1',[group.group_id])).rows[0].n,1);
});

test('cleanup purges expired data without extending eligibility or resurrecting expired retries',async () => {
  const id=await seed(); const group=await committed(id,{zip_home:'75223'});
  await run("UPDATE operation_groups SET undo_expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[group.group_id]);
  await run('SELECT operation_cleanup()');
  assert.equal((await run('SELECT * FROM operation_items WHERE group_id=$1',[group.group_id])).rows.length,0);
  const metadata=(await run('SELECT source,event_id FROM operation_groups WHERE id=$1',[group.group_id])).rows[0]; assert.equal(metadata.source,'expired'); assert.equal(metadata.event_id,null);
  await error(service.undo(actor,group.group_id,randomUUID()),410,'UNDO_EXPIRED');
  const oldId=uuid7(Date.now()-91*86_400_000); const oldGroup=randomUUID();
  await run("INSERT INTO operation_groups(id,owner_uid,client_action_id,source,action_type,manifest,begin_hash,payload_bytes,created_at,begin_retry_expires_at) VALUES($1,$2,$3,'old','save','[]','none',0,clock_timestamp()-interval '91 days',clock_timestamp()-interval '1 day')",[oldGroup,actor.uid,oldId]);
  await run('SELECT operation_cleanup()'); assert.equal((await run('SELECT id FROM operation_groups WHERE id=$1',[oldGroup])).rows.length,0);
  await error(begin([item('contacts',id)],actor,{client_action_id:oldId}),410,'RETRY_HORIZON_EXPIRED');
  await error(service.commit(actor,oldGroup,randomUUID()),404,'GROUP_NOT_FOUND');
});

test('safe BIGINT formatting and OpenAPI/browser contracts remain usable',() => {
  assert.deepEqual(formatResponseIntegers({id:'9223372036854775807',contact_id:'17',commit_order:'100'}),{id:'9223372036854775807',contact_id:17,commit_order:'100'});
  assert.ok(swaggerDocument.paths['/api/operation-groups'].get);
  for(const resource of ['contacts','checkins']) {const path=swaggerDocument.paths[`/api/${resource}/{id}`]; assert.ok(path.put.responses[202]); assert.ok(path.delete.parameters.some((p:any)=>p.name==='X-Operation-Group'));}
  assert.ok(swaggerDocument.components.schemas.UpdateCheckinDTO.properties.submitted_on);
  assert.equal(swaggerDocument.components.schemas.UpdateContactDTO.required,undefined);
  assert.ok((corsOptions.allowedHeaders as string[]).includes('If-Match')); assert.ok((corsOptions.exposedHeaders as string[]).includes('ETag'));
});


test('clock-skew cleanup gap cannot recreate an action whose begin horizon is still valid',async () => {
  const id=await seed(); const body={client_action_id:uuid7(Date.now()+240_000),source:'event-view',action_type:'save',event_id:'1',manifest:[item('contacts',id)]};
  const group=await service.begin(actor,body,randomUUID());
  await run("UPDATE operation_groups SET created_at=clock_timestamp()-interval '91 days',open_expires_at=clock_timestamp()-interval '90 days' WHERE id=$1",[group.group_id]);
  await run('SELECT operation_cleanup()');
  assert.equal((await run('SELECT id FROM operation_groups WHERE id=$1',[group.group_id])).rows.length,1);
  assert.equal((await service.begin(actor,body,randomUUID())).group_id,group.group_id);
});

test('server history can paginate more than 100 actions without browser snapshots',async () => {
  const id=await seed(); const manifest=JSON.stringify([item('contacts',id)]);
  for(let order=1;order<=101;order++) await run("INSERT INTO operation_groups(id,owner_uid,client_action_id,source,action_type,event_id,manifest,begin_hash,payload_bytes,state,committed_at,undo_expires_at,commit_order) VALUES($1,$2,$3,'many-actions','save',1,$4,'fixture',0,'undone',clock_timestamp(),clock_timestamp()+interval '30 days',$5)",[randomUUID(),'pagination-account',uuid7(),manifest,order]);
  const user={uid:'pagination-account',staff:false}; const first=await service.history(user,{source:'many-actions',limit:100});
  assert.equal(first.items.length,100); assert.equal(first.items[0].commit_order,'101'); assert.ok(first.next_cursor);
  const last=await service.history(user,{source:'many-actions',limit:100,cursor:first.next_cursor}); assert.equal(last.items.length,1); assert.equal(last.items[0].commit_order,'1');
});

test('HTTP app mounts history/auth, revision reads, and browser staging preflight',async () => {
  const id=await seed(); const originalQuery=pool.query; const originalKeys=process.env.API_KEYS_JSON; const originalEnvironment=process.env.NODE_ENV;
  (pool as any).query=run; process.env.API_KEYS_JSON=JSON.stringify([{key:'synthetic-test-key'}]); process.env.NODE_ENV='test';
  const server=createApp().listen(0,'127.0.0.1'); await once(server,'listening');
  const address=server.address() as {port:number}; const origin=`http://127.0.0.1:${address.port}`;
  try {
    const denied=await fetch(`${origin}/api/operation-groups?source=event-view`,{headers:{'X-API-Key':'synthetic-test-key'}}); assert.equal(denied.status,401);
    for (const [path,method] of [['/api/checkins','POST'],['/api/events/1','PUT']]) {
      const unsupported=await fetch(`${origin}${path}`,{method,headers:{'X-API-Key':'synthetic-test-key','X-Operation-Group':randomUUID(),'Content-Type':'application/json'},body:JSON.stringify({event_id:1,contact_id:id})});
      assert.equal(unsupported.status,400); assert.equal((await unsupported.json()).error,'UNSUPPORTED_GROUP_MUTATION');
    }
    const read=await fetch(`${origin}/api/checkins/${id}`,{headers:{'X-API-Key':'synthetic-test-key'}}); assert.equal(read.status,200); assert.ok(read.headers.get('etag')); assert.equal((await read.json()).is_self,false);
    const list=await fetch(`${origin}/api/checkins?event_id=1&contact_id=${id}&include_contact=full`,{headers:{'X-API-Key':'synthetic-test-key'}}); const rows=await list.json(); assert.equal(list.status,200); assert.notEqual(rows[0].contact.name,'JANE DOE'); assert.equal(rows[0].contact.emails,null);
    const preflight=await fetch(`${origin}/api/checkins/${id}`,{method:'OPTIONS',headers:{Origin:'http://localhost:5173','Access-Control-Request-Method':'PUT','Access-Control-Request-Headers':'x-operation-group,if-match,idempotency-key'}}); assert.equal(preflight.status,204); assert.match(preflight.headers.get('access-control-allow-headers')!,/X-Operation-Group/i);
  } finally {
    await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve())); (pool as any).query=originalQuery;
    if(originalKeys===undefined) delete process.env.API_KEYS_JSON; else process.env.API_KEYS_JSON=originalKeys;
    if(originalEnvironment===undefined) delete process.env.NODE_ENV; else process.env.NODE_ENV=originalEnvironment;
  }
});
