BEGIN;

-- JSONB retains the nested schemas without requiring PostgreSQL extensions.
CREATE FUNCTION representatives_valid_array(value jsonb, kind text)
RETURNS boolean LANGUAGE plpgsql IMMUTABLE STRICT AS $$
DECLARE
  item jsonb;
  field text;
  fields text[];
BEGIN
  IF jsonb_typeof(value) <> 'array' THEN RETURN false; END IF;
  CASE kind
    WHEN 'emails' THEN fields := ARRAY['label', 'email', 'when_to_use'];
    WHEN 'phones' THEN fields := ARRAY['label', 'phone', 'when_to_use'];
    WHEN 'social_accounts' THEN fields := ARRAY['type', 'handle', 'url'];
    WHEN 'elections' THEN fields := ARRAY['label', 'date', 'early_vote_start', 'early_vote_end', 'status'];
    ELSE RETURN false;
  END CASE;

  FOR item IN SELECT jsonb_array_elements(value) LOOP
    IF jsonb_typeof(item) <> 'object' THEN RETURN false; END IF;
    FOREACH field IN ARRAY fields LOOP
      IF jsonb_typeof(item -> field) IS DISTINCT FROM 'string' THEN RETURN false; END IF;
    END LOOP;
    IF kind = 'phones' THEN
      IF (item ->> 'phone') !~ '^[0-9]{10}$'
        OR jsonb_typeof(item -> 'can_sms') IS DISTINCT FROM 'boolean'
      THEN RETURN false; END IF;
    ELSIF kind = 'social_accounts' THEN
      IF NOT (item ->> 'type' = ANY(ARRAY[
        'Facebook page', 'Facebook profile', 'Facebook group',
        'Instagram', 'X/Twitter', 'LinkedIn', 'Bluesky'
      ])) THEN RETURN false; END IF;
    ELSIF kind = 'elections' THEN
      IF item - fields <> '{}'::jsonb THEN RETURN false; END IF;
      FOREACH field IN ARRAY ARRAY['date', 'early_vote_start', 'early_vote_end'] LOOP
        IF (item ->> field) !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' THEN RETURN false; END IF;
        BEGIN
          PERFORM (item ->> field)::date;
        EXCEPTION WHEN datetime_field_overflow OR invalid_datetime_format THEN
          RETURN false;
        END;
      END LOOP;
    END IF;
  END LOOP;
  RETURN true;
END $$;

CREATE FUNCTION representatives_valid_polygon(value jsonb)
RETURNS boolean LANGUAGE plpgsql IMMUTABLE STRICT AS $$
DECLARE
  ring jsonb;
  position jsonb;
  coordinate jsonb;
  dimensions integer;
BEGIN
  IF jsonb_typeof(value) <> 'object'
    OR value ->> 'type' IS DISTINCT FROM 'Polygon'
    OR jsonb_typeof(value -> 'coordinates') IS DISTINCT FROM 'array'
  THEN RETURN false; END IF;
  IF jsonb_array_length(value -> 'coordinates') = 0 THEN RETURN false; END IF;

  FOR ring IN SELECT jsonb_array_elements(value -> 'coordinates') LOOP
    IF jsonb_typeof(ring) <> 'array' THEN RETURN false; END IF;
    IF jsonb_array_length(ring) < 4 OR ring -> 0 <> ring -> -1 THEN RETURN false; END IF;
    FOR position IN SELECT jsonb_array_elements(ring) LOOP
      IF jsonb_typeof(position) <> 'array' THEN RETURN false; END IF;
      IF jsonb_array_length(position) < 2 THEN RETURN false; END IF;
      IF dimensions IS NULL THEN dimensions := jsonb_array_length(position); END IF;
      IF jsonb_array_length(position) <> dimensions THEN RETURN false; END IF;
      FOR coordinate IN SELECT jsonb_array_elements(position) LOOP
        IF jsonb_typeof(coordinate) <> 'number' THEN RETURN false; END IF;
      END LOOP;
    END LOOP;
  END LOOP;
  RETURN true;
END $$;

CREATE TABLE representatives (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity text,
  body text,
  title text,
  name text,
  bio text,
  webpage_url text,
  photo_url text,
  emails jsonb DEFAULT '[]'::jsonb,
  phones jsonb DEFAULT '[]'::jsonb,
  social_accounts jsonb DEFAULT '[]'::jsonb,
  elections jsonb DEFAULT '[]'::jsonb,
  "start" timestamp without time zone,
  "end" timestamp without time zone,
  district text,
  district_description text,
  district_bounds jsonb,
  CONSTRAINT representatives_emails_check CHECK (representatives_valid_array(emails, 'emails')),
  CONSTRAINT representatives_phones_check CHECK (representatives_valid_array(phones, 'phones')),
  CONSTRAINT representatives_social_accounts_check CHECK (representatives_valid_array(social_accounts, 'social_accounts')),
  CONSTRAINT representatives_elections_check CHECK (representatives_valid_array(elections, 'elections')),
  CONSTRAINT representatives_district_bounds_check CHECK (representatives_valid_polygon(district_bounds))
);

COMMIT;
